### ISSUE TITLE
PK/RK for Table Storage entities

### ISSUE THREAD

**Issue by rickvdbosch** [Layla-P/HacktoberfestProject#15]
For the Table Storage entities `RepositoryEntity` and `PrEntity` there are no PartitionKey or RowKey (strategies) defined yet. UserEntity, has `Users` as the PartitionKey and takes `UserId.ToString()` as the RowKey.

Will we be using static PartitionKeys (like `Users` for all users) for all table storage entities? This will help in having multiple types of entities in one table, but if we get to large amounts of users it *might* not help in performance if there are scenario's where we need to query entities other than all entities or a specific one.

**Comment by rickvdbosch** [comment]
Another question about the `UserEntity` Table Storage entity: it currently has a Guid as the `Id`, but the GitHub information does not contain a Guid we could use for this.

There *is* an `Id` field available which we could use. This is a numerical value (in my case it's 8 characters long), or we could use the login/username.

My recommendation would be to use **login** since it's unique and also says something about the actual user. Is this OK?

**Comment by CrypticEngima** [comment]
@rickvdbosch  we have updated the userentity as i misunderstood the data comming from the GithubAPI. We are using the static "users" Partition as from what i understand it will lock down to indexing only needed on the rowkey. the userid field has been updated to github login  as yes it's the unique key from github
