### ISSUE TITLE
Feature: Add PR view

### ISSUE THREAD

**Issue by Layla-P** [Layla-P/HacktoberfestProject#21]
** Description: **
Use the existing add.cshtml and add method on the Homecontroller to log a PR

** Steps: **

Fields to capture
```
Username
Owner
Repository
PR number
PR URL
```
We have a DTO prepared for this:
https://github.com/Layla-P/HacktoberfestProject/blob/dev/HacktoberfestProject.Web/Models/DTOs/User.cs
The username will be captured from the HttpContext so no need to have a field for it.

In the Add Method on the Controller, we will use the TableService to save the new PR

**Comment by napalm684** [comment]
I'll take this.

**Comment by rickvdbosch** [comment]
This one is closed, right? PR #24 closes this.

**Comment by napalm684** [comment]
@Layla-P had review feedback. I implemented some but had some questions about other points that were raised in that original PR.

**Comment by napalm684** [comment]
@Layla-P do you mind looking at the remaining comments on https://github.com/Layla-P/HacktoberfestProject/pull/24
I think there is one there for @CrypticEngima too

**Comment by CodeItQuick** [comment]
Hello - If you add the text: "Fix #21 " to the relevant PR description it will add it to that issues discussion and close the issue when complete

Looks like it already got merged as well.
