### ISSUE TITLE
Add Table Storage with Cosmos DB API

### ISSUE THREAD

**Issue by Layla-P** [Layla-P/HacktoberfestProject#3]
Use this repo as a template perhaps:
https://github.com/Layla-P/LittleWins/tree/master/LittleWins/Data

**Comment by CrypticEngima** [comment]
I was thinking something like this for the table storage to make it very simple  and use the Github API to get the details.   

{
     "id": "GitHub Guid",
    "repo":[
        {
        "id":"Github Guid",
        "owner":"Github Guid ",
        "prs":[
            {
                "id":"Github Guid"
            }
        ]
        }
    ]
}

**Comment by Layla-P** [comment]
This structure looks good

**Comment by Layla-P** [comment]
That structure looks good!
