### ISSUE TITLE
Index page view when Authenticated

### ISSUE THREAD

**Issue by Layla-P** [Layla-P/HacktoberfestProject#4]
One a user has authenticated show the following on the home/index view.

1. Check if this is their first time on the site - if so, prompt them to register
2. If they are returning show them their recorded PRs
3. Button to allow user to add new PR to their record - this will navigate to another view with a form

**Comment by rickvdbosch** [comment]
I'll pick up this one (at least partially 😋)

**Comment by rickvdbosch** [comment]
1 and 2 are done with PR #4.  
We do still need to have a way for a user to actually register.  
3. should be done somewhere today.

**Comment by CrypticEngima** [comment]
@Layla-P @rickvdbosch   Do we need a registration if we are using Github authentication? should we place a comment on the index page when not logged in to say "If you wish to participate please use your github login with the login button above. If you dont have a github account please go to [https://github.com](https://github.com) and complete the sign in process. happy hacking!!"  or some thing of the sort?

**Comment by rickvdbosch** [comment]
My idea would be that registering a PR will automatically register the user if they are not in the system yet. I would also like to have a look if we can get all (open?) PRs of a GitHub user from GitHub so they only need to check a box to register it with HacktoberfestProject.

**Comment by Layla-P** [comment]
@rickvdbosch I'm not sure I follow... Are you saying not to have a login with GitHub button?

This is how I see it working with our current architecture:

Arrive at sight - login with GitHub whether first time on site or not - they don't need to specifically register with the way we have stuff set up now.

Then we can show all the PRs they have logged on the site and then an add button.

So @rickvdbosch they would have a user record created as soon as they log a PR, which is what I think you are saying. So I think we are all on the same page :-)

As to pulling back all open PRs, I haven't seen that on the User API. Add it as a feature request and we can get to it in time :-)

For now, let's just go with the form that we have.

**Comment by rickvdbosch** [comment]
>Are you saying not to have a login with GitHub button?

No! Let's keep the *login* button. 😁 There's just no reason to explicitly ask them to register, right? Like you said, 

>they don't need to specifically register with the way we have stuff set up now.

So let's get some code in 👏🏻

**Comment by rickvdbosch** [comment]
I think this issue is done, too. (See PRs #23 and #24). It can be closed.
